---
- name: Install a webserver
  hosts: web
  become: true
  tasks:
    - name: Ensure nginx is disabled and not running
      ansible.builtin.service:
        name: nginx
        enabled: false
        state: stopped

    - name: Remove nginx
      ansible.builtin.package:
        name: nginx
        state: absent
