---
- name: Copy nginx config file to webserver
  hosts: web
  become: true
  tasks:
    - name: Copy over config file
      ansible.builtin.copy:
        src: files/example.internal.conf
        dest: /etc/nginx/conf.d/example.internal.conf
        mode: "0755"
        owner: root
      register: result_conf

    - name: Create content directory
      ansible.builtin.file:
        path: /var/www/example.internal/html/
        state: directory
        mode: "0755"
        owner: root

    - name: Copy over index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/example.internal/html/index.html
        mode: "0644"
        owner: root
      register: result_html

    # Ensure that webserver always listens to the external interface
    - name: Render config file from jinja2 template
      ansible.builtin.template:
        src: templates/example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        mode: "0755"
        owner: root

    - name: Restart nginx to use the new config file
      when: result_conf is changed or result_html is changed
      ansible.builtin.service:
        name: nginx.service
        state: restarted
        enabled: true
