$ANSIBLE_VAULT;1.1;AES256
63626564636166326166343566653838643266663262623034303738323534363937363330623530
6536316236323630356533613562633234363437303630640a666161323330616534653639643764
65653862316362323635313939663939343862656235656336396165323731626635666332316562
3937313231316633310a323966623039326639303065633365393838623765326235616361613930
39393935326230376162633738326663643936646333303137363562393765316339
